---
- name: Configure Web Servers
  hosts: web_servers
  become: yes
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

